### ISSUE TITLE
Surveys unable to proceed to the next page when using branching logic 

### ISSUE THREAD

**Issue by cjbrancato** [ctsit/auto_populate_fields#25]
We updated to version 2.4.0 and began having issues with surveys that contain branching logic.  The issue occurs when trying to go to the "Next Page" of the survey.  For example, if the survey is supposed to branch to a question on page 2 based on a response of "Yes" to the first question or branches to page 3 based on a response of "No" to the first question, the survey hangs and will not go to the next page.  It generates a Javascript error and I think it is related to the `formSubmitDataEntry` function.

I believe it is related to #23 where surveys were included.

**Comment by pbchase** [comment]
@cjbrancato, do you have some screenshots of the javascript errors you can share? Perhaps and XML export of the project wherein you had the issue? Anything that might help us see what you see and reproduce the errors would be helpful.

**Comment by pbchase** [comment]
@cjbrancato, do you have any screenshots of the error? It would also be helpful to get an XML export of a project wherein you can reproduce the error. 

If you want us to prioritize this work, please make it easier for us to reproduce and visualize the error. Help us help you.

**Comment by ChrWelker** [comment]
I have a similar problem.
Though my example is not beautiful, it might help you to fix the problem.
A further question: I'd need the auto-populate function for repeated events. Is there a plan to implement this function
[Auto_Populate_Survey_Problem.zip](https://github.com/ctsit/auto_populate_fields/files/4354427/Auto_Populate_Survey_Problem.zip)

**Comment by pbchase** [comment]
@ChrWelker, thanks so much for sending an example. I used your project XML file in an attempt to replicate the error you show in your screenshots, but I never got the error.  I have attached a series of screenshots that show the steps I moved through. This is with APF 2.5.0 on REDCap 9.7.0. Did I replicate your steps correctly? Did I match your configuration close enough? 

[apf 250 test on rc 970.zip](https://github.com/ctsit/auto_populate_fields/files/4354626/apf.250.test.on.rc.970.zip)

As to us adding support for repeating forms, my advice to everyone for any feature you want added or bug you want fixed in any of our modules is the same: help us help you. I recommend these steps:

1) Open a new issue on that module in Github
2) Describe what the software does now and contrast that to what you want the software to do. Screenshots are very helpful. Describing the behavior in the body of the issue is better than as an attachment. 
3) Provide a simple example REDCap project in the form of REDCap XML export that illustrates what the software does now. Include the data in the XML file or as a CSV export if that would be helpful. 
4) Be available to answer follow up questions

Again, thanks so much for your input.

**Comment by ChrWelker** [comment]
I have APF 2.5.0 (same config as your screenshot shows) on REDCap 9.1.1 - maybe this is a relevant difference? I still have the error, and it occurs in any case when I press the Next Page Button at the first page of the survey (no difference data entered or not). Using Firefox it occurs only when I first visit the page of the survey. When I leave the survey (save data, no matter whether with or without entered data), and open the survey for a second time, there is no error any more. Nevertheless, at the second survey page I get the error again. Even worse, on my iPad (Safari) there is no way to save data, and (Buttons Next Page and Save and Return Later both become "dead" when pressed) I can't get passed the first page. Moreover, in any case, the Previous Page Button and also the Save an Return Later Button lead to the NEXT page. Can you replicate this?
[1505_Auto_Populate_Survey_Problem.zip](https://github.com/ctsit/auto_populate_fields/files/4355025/1505_Auto_Populate_Survey_Problem.zip)

**Comment by ChrWelker** [comment]
Upgraded to REDCap 9.7.8 - everything ok!

**Comment by pbchase** [comment]
@ChrWelker, thanks for the info. What you are reporting blows my mind, but I expect it will improve our product.

I was doing code review on @ChemiKyle's fixes to this bug yesterday when we had to switch gears onto a very high priority covid-19 project. I think we can come for air on Tuesday next week and resume our work on this. #covid19rulesmyworld

**Comment by pbchase** [comment]
@ChrWelker, I got this issue mixed up with the another one. Sorry. I have too many balls in the air.

**Comment by pbchase** [comment]
As we cannot duplicate this issue and @ChrWelker says it goes away in REDCap 9.7.8, we are going to close the issue.
